config/routes.rb
Rails.application.routes.draw do

  root to: 'home#show'

  resources :games
  
  resources :players, except: [:show]

  resources :teams

  resources :pitches

  get "at_bats/at_bat_pitches_data" => "at_bats#at_bat_pitches_data"

  get "/" => "players#welcome", as: :welcome

  get "players" => "players#index"
  
  get "players/batters" => "players#batters"

  get "players/matchups" => "players#matchups"

  get "players/pitches_data" => "players#pitches_data"

  get "players/batter_list" => "players#batter_list"

  get "ops_leaders" => "players#ops_leaders"

  get "home_run_leaders" => "players#home_run_leaders"

  get "strikeout_leaders" => "players#strikeout_leaders"

end

app/models/pitch.rb
# == Schema Information
#
# Table name: pitches
#
#  id         :integer          not null, primary key
#  at_bat_id  :integer
#  result     :string
#  pitch_type :string
#  nasty      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Pitch < ActiveRecord::Base
  belongs_to :at_bat
  has_one :baserunner
  has_one :movement
  has_one :release_point
  has_one :strike_zone
  has_one :velocity

  def inning
    self.atbat.inning
  end

  def game
    self.inning.game
  end

  def batter
    self.atbat.batter_id
  end

  def pitcher
    self.atbat.pitcher_id
  end
  
  def pitches(pitcher_id)
    AtBat.where(pitcher_id: pitcher_id).each_with_object({}) do |at_bat, hash|
      pitches = at_bat.pitches
    end
  end

end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_action :set_pitch, only: [:show, :edit, :update, :destroy]

  def index
    if params[:pitcher_id]
      @pitcher = Player.find_by(player_id: params[:pitcher_id])
      @pitches = @pitcher.pitches
    end
    
    respond_to do |format|
      format.html
      format.json { render :json => {pitches: @pitches} }
    end
  end

  private
    def set_pitch
      @pitch = Pitch.find(params[:id])
    end

    def pitch_params
      params[:pitch]
    end
end

app/views/pitches/_form.html.erb
<%= form_for(@pitch) do |f| %>
  <% if @pitch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pitch.errors.count, "error") %> prohibited this pitch from being saved:</h2>

      <ul>
      <% @pitch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pitches/edit.html.erb
<h1>Editing Pitch</h1>

<%= render 'form' %>

<%= link_to 'Show', @pitch %> |
<%= link_to 'Back', pitches_path %>

app/views/pitches/index.html.erb
<p id="notice"><%= notice %></p>


 <% @pitch_types = [["FA", "Fast Ball"], ["FF", "Four-Seam Fast Ball"], ["FT", "Two-Seam Fast Ball"], ["FC", "Fast Cutter"], ["FS", "Fast Ball Sinker"], ["SI", "Sinker"], ["SL", "Slider"], ["CH", "Changeup"], ["CU", "Curve Ball"], ["KC", "Knuckle-Curve"], ["KB", "Knuckleball"], ["EP", "Eephus"]] %>

<center>
<h1>Pitch Distribution</h1>
<form id="pitches_form">
  <p>
  <select id="pitchers">
      <option value="choose_pitcher">Choose A Pitcher</option>
      <% Player.pitchers.sort_by{|id| Player.find_by(player_id: id).last}.each do |pitcher| %>
        <option value="<%=pitcher%>"> <%= "#{Player.find_by(player_id: pitcher).first} #{Player.find_by(player_id: pitcher).last}" %> </option> %>
      <% end %>
    </select>
  </p>
  <div>
    <% @pitch_types.each do |type| %>
      <%= check_box_tag type[1], type[0], {class: "pitch_type_checkbox", checked: false} %>
      <%= type[1] %>
    <% end %>
  </div>
</form>

</center>

<!-- create container element for visualization -->
<div>
  <span id="pitch_type_list"></span>
  <span id="batters-box"></span>
<!-- load D3js -->
</div>

app/views/pitches/new.html.erb
<h1>New Pitch</h1>

<%= render 'form' %>

<%= link_to 'Back', pitches_path %>

app/views/pitches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pitch_path(@pitch) %> |
<%= link_to 'Back', pitches_path %>