config/routes.rb
Rails.application.routes.draw do

  root to: 'home#show'

  resources :games
  
  resources :players, except: [:show]

  resources :teams

  resources :pitches

  get "at_bats/at_bat_pitches_data" => "at_bats#at_bat_pitches_data"

  get "/" => "players#welcome", as: :welcome

  get "players" => "players#index"
  
  get "players/batters" => "players#batters"

  get "players/matchups" => "players#matchups"

  get "players/pitches_data" => "players#pitches_data"

  get "players/batter_list" => "players#batter_list"

  get "ops_leaders" => "players#ops_leaders"

  get "home_run_leaders" => "players#home_run_leaders"

  get "strikeout_leaders" => "players#strikeout_leaders"

end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  player_id  :integer
#  first      :string
#  last       :string
#  num        :string
#  rl         :string
#  bats       :string
#  position   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Player < ActiveRecord::Base

  def self.players(limit)
    unless limit > 0
      limit = 5
    end
    Player.order(:last).limit(limit).pluck(:first, :last)
  end

  def self.matchups(pitcher_id, batter_id)
    at_bats = AtBat.where(pitcher_id: pitcher_id, batter_id: batter_id)
    at_bats.each_with_object([]) do |at_bat, arr|
      game = "#{at_bat.inning.home_team} vs. #{at_bat.inning.away_team}"
      inning = at_bat.inning.number
      result = at_bat.event
      date = at_bat.game_date[0..9]
      arr.push({game: game, inning: inning, result: result, date: date, at_bat_id: at_bat.id})
    end
  end

  def self.pitchers
    AtBat.all.pluck(:pitcher_id).uniq
  end

  def self.top_5_home_run_hitters
    ascending_array = Player.all.sort_by {| player| player.home_run_total }
    descending_array = ascending_array.reverse
    top_ten = descending_array[0..9]
    top_ten.each_with_object([]) do |player, array|
      full_name = "#{player.first} #{player.last}"
      hash = {name: full_name, home_runs: player.home_run_total}
      array.push(hash)
    end
  end

  def self.top_5_stike_out_pitchers
    ascending_array = Player.all.sort_by {| player| player.strike_out_total }
    descending_array = ascending_array.reverse
    top_ten = descending_array[0..9]
    top_ten.each_with_object([]) do |player, array|
      full_name = "#{player.first} #{player.last}"
      hash = {name: full_name, strike_outs: player.strike_out_total}
      array.push(hash)
    end
  end

  def self.top_10_ops
    ascending_array = Player.all.sort_by {| player| player.ops }
    descending_array = ascending_array.reverse
    top_ten = descending_array[0..9]
    top_ten.each_with_object([]) do |player, array|
      full_name = "#{player.first} #{player.last}"
      hash = {name: full_name, ops: player.ops}
      array.push(hash)
    end
  end

  def batters_faced
    batter_ids = AtBat.where(pitcher_id: self.player_id).pluck(:batter_id).uniq
    batter_ids.each_with_object([]) do |batter, arr|
      player = Player.find_by(player_id: batter)
      name = "#{player.first} #{player.last}"
      arr.push({id: batter, name: name})
    end
  end

  def pitches
    at_bats = AtBat.where(pitcher_id: self.player_id)
    pitches = at_bats.each_with_object([]) do |at_bat, arr|
      at_bat.pitches.each do |pitch|
        arr.push({x: pitch.strike_zone.x, y: pitch.strike_zone.y, type: pitch.pitch_type})
      end
    end
  end

  def plate_appearances
    AtBat.where(batter_id: self.player_id)
  end

  def total_plate_appearances
    if plate_appearances
      plate_appearances.count.to_f
    else
      0.0000000
    end
  end

  def singles_total
    if plate_appearances
      plate_appearances.where(event: "Single").count.to_f
    else
      0.0000000
    end
  end

  def doubles_total
    if plate_appearances
      plate_appearances.where(event: "Double").count.to_f
    else
      0.0000000
    end
  end

  def triples_total
    if plate_appearances
      plate_appearances.where(event: "Triple").count.to_f
    else
      0.0000000
    end
  end

  def home_run_total
    if plate_appearances
      plate_appearances.where(event: "Home Run").count.to_f
    else
      0.0000000
    end
  end

  def walks_total
    if plate_appearances
      plate_appearances.where(event: "Walk").count.to_f
    else
      0.0000000
    end
  end

  def sac_fly_total
    if plate_appearances
      plate_appearances.where(event: "Sac Fly").count.to_f
    else
      0.000000
    end
  end

  def sac_bunt_total
    if plate_appearances
      plate_appearances.where(event: "Sac Bunt").count.to_f
    else
      0.000000
    end
  end

  def hbp_total
    if plate_appearances
      plate_appearances.where(event: "Hit By Pitch").count
    else
      0.0000000
    end
  end

  def sac_total
    sac_bunt_total + sac_fly_total
  end

  def total_hits
    hits = singles_total + doubles_total + triples_total + home_run_total
    hits
  end

  def total_bases
    total_bases = singles_total + (2 * doubles_total) + (3 * triples_total) + (4 * home_run_total)
    total_bases
  end

  def total_abs
    without_walks = total_plate_appearances - walks_total
    without_hbp = without_walks - hbp_total
    abs = without_hbp - sac_total
    abs
  end

  def slg
    if self.total_abs == 0
      return 0.0
    end
    slg = total_bases.to_f/total_abs.to_f
  end

  def obp
    if self.total_abs < 10
      return 0.0
    end
    top = (total_hits + walks_total + hbp_total)
    bottom = (total_abs + walks_total + sac_total + hbp_total)
    obp = top.to_f/bottom.to_f
  end

  def ops
    ops = slg + obp
  end

  def strike_out_total
    AtBat.where(pitcher_id: self.player_id, event: "Strikeout").count
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def matchups
    @matchups = Player.matchups(params[:pitcher_id], params[:batter_id])
    render :json => {matchups: @matchups}
  end

  def at_bat_pitches_data
    @pitches_data = Player.at_bat_pitches(params[:at_bat_id])
    render :json => {pitches_data: @pitches_data}
  end

  def pitches_data
    @at_bat = AtBat.find(params[:at_bat_id])
    @pitches_data = @at_bat.pitches_data
    render :json => {pitches_data: @pitches_data, at_bat_id: @at_bat.id}
  end

  def batters
    @pitcher = Player.find_by(player_id: params[:pitcher_id])
    @batters = @pitcher.batters_faced
    render :json => {batters: @batters}
  end

  def strikeout_leaders
    @rankings = Player.top_5_stike_out_pitchers
    respond_to do |format|
      format.html
      format.json {render :json => {:rankings => @rankings}}
    end
  end

  def home_run_leaders
    @rankings = Player.top_5_home_run_hitters
    respond_to do |format|
      format.html
      format.json {render :json => {:rankings => @rankings}}
    end
  end

  def ops_leaders
    @rankings = Player.top_10_ops
    respond_to do |format|
      format.html
      format.json {render :json => {:rankings => @rankings}}
    end
  end
end

app/views/players/create.html.erb
<h1>Players#create</h1>
<p>Find me in app/views/players/create.html.erb</p>

app/views/players/home_run_leaders.html.erb
<body>
  <center>
    <h1>Top 10 Home Run Hitters 2015 Playoffs</h1>
    <canvas id="home-run-chart" width="800" height="800"></canvas>
  </center>
</body>

<%= javascript_include_tag "Chart" %>
<%= javascript_include_tag "top_home_run_hitters" %>

app/views/players/index.html.erb
<form id="matchup_form" style="padding-top: 9%;">
<center>
  <select id="pitcher_id" style="width: 20%;height:4em">
    <option value="choose_pitcher">Choose A Pitcher</option>
      <% Player.pitchers.each do |pitcher| %>
        <option value="<%=pitcher%>"> <%= "#{Player.find_by(player_id: pitcher).first} #{Player.find_by(player_id: pitcher).last}" %> </option> %>
      <% end %>
  </select>

  <select id="batter_id" style="width: 20%;height:4em">
    <option>Select Batter</option>
  </select>
</center>
</form>

<center><button class='sequence-button-js hidden'> Show Sequence </button></center>
<div id="batters-box"></div>
<div id="pitches-table"></div>


<%= javascript_include_tag "application" %>

app/views/players/ops_leaders.html.erb
<body>
  <center>
    <h1>Top 10 OPS in 2015 Playoffs</h1>
    <canvas id="ops-leader-chart" width="800" height="800"></canvas>
  </center>
</body>

<%= javascript_include_tag "Chart" %>
<%= javascript_include_tag "ops_leaders" %>

app/views/players/show.html.erb
show.html.erb

app/views/players/strikeout_leaders.html.erb
  <body>
  <center>

    <h1>Top 10 Strikeout Totals by Pitcher 2015 Playoffs</h1>
    <canvas id="strike-out-chart" width="800" height="800"></canvas>
    
  </center>
  </body>
  
<%= javascript_include_tag "Chart" %>
<%= javascript_include_tag "strikeout_leaders" %>

app/views/players/welcome.html.erb
<%= link_to 'Home Run Leaders', home_run_leaders_path %>
<%= link_to 'Strike Out Leaders', strikeout_leaders_path %>
<%= link_to 'At Bat Matchups', players_path %>